
name: malaz
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  pin_code_fields: ^8.0.1
  intl: any
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  image_picker: ^1.2.1
  path: ^1.9.1
  dotted_border: ^3.1.0
  get_it: ^7.7.0
  dio: ^5.5.0+1
  internet_connection_checker: ^1.0.0+1
  go_router: ^14.2.0
  dartz: ^0.10.1
  modal_progress_hud_nsn: ^0.5.1
  another_flushbar: ^1.12.32
  curved_navigation_bar: ^1.0.6
  shimmer: ^3.0.0
  path_provider: ^2.1.5
  flutter_secure_storage: ^10.0.0
  #cached_network_image: ^3.4.1
  table_calendar: ^3.0.9
  google_nav_bar: any
  lottie: ^3.1.0
  location: ^6.0.2
  geocoding: ^4.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  pusher_channels_flutter: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/key_logo.png
    - assets/lottie/sending_booking.json
    - assets/lottie/filter_lottie.json
    - assets/lottie/filter_lottie_v1.json
    - assets/lottie/gold_verified_lock.json
    - assets/lottie/key_lock_person_widgets.json
    - assets/lottie/key_lock_setting_person_mobile.json
    - assets/lottie/shake_hands.json
    - assets/lottie/house_paper.json
    - assets/lottie/shake_share_laptop.json
    - assets/lottie/search_on_tablet.json
