
name: malaz
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  pin_code_fields: ^8.0.1
  intl: any
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  image_picker: ^1.2.1
  path: ^1.9.1
  dotted_border: ^3.1.0
  get_it: ^7.7.0
  dio: ^5.5.0+1
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/key_logo.png
    - assets/icons/ribbon.png
    - assets/icons/card_box.png
